# Frontend-only deploy on Netlify. Adjust api_url to your backend.
[build]
  base = "web-app"
  command = "npm run build"
  publish = "dist"
  [build.environment]
    NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_BACKEND_HOST/api/:splat"
  status = 200
  force = true
